HTML design changed
ok-technopolis-autumn-2019/Kamil_Kadyrov pull request #1
Opened 2019-10-08 11:17 UTC by Kopeyka885

Deleted img tags, added buttons, sections and restructured the whole model

2019-10-09 06:33 UTC, fromanywhere requested changes

2019-10-09 06:33 UTC, fromanywhere commented on index.html
> +        <section class="main-content__search-input search-input">
Оно здесь не search, оно здесь post, add

2019-10-09 06:33 UTC, fromanywhere commented on index.html
> +              <div class="list-item__view">
Если здесь редактируемое поле лежит в плоском списке, то неясно, в чем функция list-item__view

2019-10-09 14:44 UTC, Kopeyka885 commented on index.html
> +        <section class="main-content__search-input search-input">
Исправил.

2019-10-09 14:44 UTC, Kopeyka885 commented on index.html
> +              <div class="list-item__view">
Добавил дополнительные div'ы для input'a, как было показано в материалах лекции

2019-10-09 15:24 UTC, Kopeyka885 reviewed
Добавил commit с комментариями об изменениях

2019-10-11 08:58 UTC, fromanywhere commented on index.html
> +              <span class="" tasks-item__text>JS</span>
атрибут вылетел из кавычек

2019-10-11 08:59 UTC, fromanywhere commented on index.html
> +  <meta charset="UTF-8" />
С форматированием конечно так себе

2019-10-11 08:59 UTC, fromanywhere approved these changes

2019-10-11 09:24 UTC, merged